### ISSUE TITLE
Release the app into F-droid

### ISSUE THREAD

**Issue by git10700** [ZTFtrue/MonsterMusic#2]

**Comment by IzzySoft** [comment]
Won't be accepted at F-Droid.org with proprietary libraries inside:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Cast (/com/google/android/gms/cast): NonFreeComp
* Google Mobile Services (/com/google/android/gms): NonFreeComp
```

I wonder why you `implement` Cast but don't seem to make use of it. Also why the description says "operates without any network requests", but the app requests the `INTERNET` permission? If you don't make use of Google Cast, I'd suggest to not include that library (not sure, maybe it's [this line](https://github.com/ZTFtrue/MonsterMusic/blob/390547efee4a8481b5cf26646c600b3c4dda93ba/app/build.gradle.kts#L92)?). My guess is that GMS will disappear then automatically, as it probably was dragged in as a dependency of Cast. That would then make your app eligible for F-Droid.

Until then: I've just added it to [my repo](https://apt.izzysoft.de/fdroid), where it will [show up](https://apt.izzysoft.de/packages/com.ztftrue.music/) with the next sync around 6 pm UTC – and look like this:

![image](https://github.com/ZTFtrue/MonsterMusic/assets/6781438/cac72f16-acc3-46fd-a4f3-62300708a36a)

If you want to, I can send you the Fastlane structures that issuebot complained about from what is set up in my repo, takes me 5 minutes to create the corresponding PR; just let me know if you want to have them.

**Comment by IzzySoft** [comment]
PS: I've just changed the short description to "A Music Player with Equalizer and more" to prepare for your update :wink:

**Comment by ZTFtrue** [comment]
I fixed this and released it here https://github.com/ZTFtrue/MonsterMusic/releases

**Comment by IzzySoft** [comment]
Just checking the logs from today's update:

    ! repo/com.ztftrue.music_14.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)

Checking the library section:

![image](https://github.com/ZTFtrue/MonsterMusic/assets/6781438/46aecb4b-df9e-4596-a549-3d9c53d6fc9e)

Looks good, thanks! Will now remove the AntiFeatures as they no longer apply. As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

IIRC, you've applied for listing at F-Droid.org. Didn't the bot complain about missing Fastlane structures there? If it did, do you want my above mentioned contribution? For clarification: your app is in *my* repo now, not in F-Droid.org's. Of course, if that's fine with you and you no longer want your listing established "over there", I won't complain :wink: Up to you.

**Comment by ZTFtrue** [comment]
Yes, welcome your contribution. and no problem established "over there"

**Comment by IzzySoft** [comment]
There you go, enjoy! As pointed out: should you have questions, be welcome to ask.

**Comment by ZTFtrue** [comment]
https://f-droid.org/zh_Hans/packages/com.ztftrue.music/

Thank you.

**Comment by IzzySoft** [comment]
You're welcome! As your app is now listed at F-Droid, and your Readme has no link to the IzzyOnDroid repo: do you want to [keep it there](https://apt.izzysoft.de/fdroid/index/apk/com.ztftrue.music)? Then you might wish to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it). Else please let me know if I shall remove it there.

**Comment by ZTFtrue** [comment]
Yes, I want to keep it there. and I will pick a badge.

**Comment by IzzySoft** [comment]
Thanks! Marked it for "keep" then, linking here as reference. Thanks also for adding the badge :star_struck:
