### ISSUE TITLE
instant crash when pitch changed

### ISSUE THREAD

**Issue by Unacceptium** [ZTFtrue/MonsterMusic#26]
the app (0.1.15(f-droid)) instantly crashes when pitch gets changed.

i have no idea if theres logs anywhere, if i find one i upload there.

my device: Honor RKY-LX1 Android12(Magic UI6)

please note that i dont know if the app is even maintained, updated or will be in future.

if testing possibilities limited, i can test but i have no PC.

Edits:
1-same when pitch gets changed
2-echo dont work too, but notification does respond without playing at all

**Comment by ZTFtrue** [comment]
I guess your audio format encoding is not  PCM 16-bit.

This is why the app crash or nor work.
```
    if (inputAudioFormat.encoding != C.ENCODING_PCM_16BIT) {
      throw new UnhandledAudioFormatException(inputAudioFormat);
    }
```

Could you provide the audio file? this will help me deal this crash and save time.

**Comment by Unacceptium** [comment]
this happens with every audio on my device. i dont have enough cloud storage to upload them all.

**Comment by ZTFtrue** [comment]
Could you try this file? download from here <https://helpguide.sony.net/high-res/sample1/v1/en/index.html>

You only need to provide an audio (some clips, not all audio to avoid copyright)。

**Comment by Unacceptium** [comment]
https://github.com/ZTFtrue/MonsterMusic/assets/145642963/0e11a6ed-fb3d-4075-9e95-2cd274c369b4

**Comment by ZTFtrue** [comment]
Please install this release https://github.com/ZTFtrue/MonsterMusic/releases/tag/0.1.15-beta.1.
I added a feature to collect crashes (https://github.com/ZTFtrue/MonsterMusic/assets/13563890/19741edd-1c11-4f94-bc61-e806a21a8221).

**Comment by Unacceptium** [comment]
this is the collected text:
[code]
sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
java.lang.Float.parseFloat(Float.java:451)
com.ztftrue.music.ui.play.EqualizerViewKt$EqualizerView$3$1$1$3.invoke(EqualizerView.kt:124)
com.ztftrue.music.ui.play.EqualizerViewKt$EqualizerView$3$1$1$3.invoke(EqualizerView.kt:119)
androidx.compose.material3.SliderState.dispatchRawDelta(Slider.kt:1833)
androidx.compose.material3.SliderState$dragScope$1.dragBy(Slider.kt:1883)
androidx.compose.foundation.gestures.DraggableNode$abstractDragScope$1.dragBy-k-4lQ0M(Draggable.kt:315)
androidx.compose.foundation.gestures.DraggableNode.draggingBy(Draggable.kt:327)
androidx.compose.foundation.gestures.AbstractDraggableNode$startListeningForEvents$1$1.invokeSuspend(Draggable.kt:437)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:68)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1621)
android.view.Choreographer.doCallbacks(Choreographer.java:1141)
android.view.Choreographer.doFrame(Choreographer.java:1007)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1585)
android.os.Handler.handleCallback(Handler.java:955)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loopOnce(Looper.java:206)
android.os.Looper.loop(Looper.java:296)
android.app.ActivityThread.main(ActivityThread.java:8971)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)
[/code]

**Comment by ZTFtrue** [comment]
Sorry, I can't fix this. I don't no why it happened. I guess because the slider return value is not a number, but I read the  slider of source code  and can't find any problem.

Maybe, you can try to update your device system.

I don't have this device `Honor RKY-LX1 Android12(Magic UI6)`, I test by other device (Android 12,MagicUI 6), this crash can't happen.

![Screenshot from 2024-04-24 19-50-52](https://github.com/ZTFtrue/MonsterMusic/assets/13563890/cefd821c-8784-4e0e-ba27-1eb2dfdc79cd)

**Comment by Unacceptium** [comment]
i close this as unsolvable

**Comment by Unacceptium** [comment]
i have no knowledge in programming at all but i guess the problem is around the slider itself and its substeps. your slider works with substeps instead ones VLC uses or almost all music apps. i guess the problem is the substeps are not where the understandable numbers are. i mean if your code understands only 1 but the slider returns 0.9891966 etc your code will go into a panic because it dont know what to do or how to handle. the music playing slider works normally because i think the music has every number understandable because the music does have every milisecond. for example, short audio, the slider sometimes go multiple steps in the same second but a hour long audio is impossible to control precisely.

**Comment by gargamel17** [comment]
Exactly same issue with Poco F1 LOS 21
