### ISSUE TITLE
Opening the folders tab crash the app.

### ISSUE THREAD

**Issue by git10700** [ZTFtrue/MonsterMusic#31]
F-droid 
App Ver: 0.1.16
Android Version: 13
Phone Model: Infinix Note 30 Vip.

I did not find debug version to attach the logs.

Thank you for developing this amazing music player.

**Comment by ZTFtrue** [comment]
Thank you for your feedback.

I fixed this, https://github.com/ZTFtrue/MonsterMusic/commit/db41554ea7b7353f8f2e1215be33e02d6ce780ba .

Now, I have released a new version. https://github.com/ZTFtrue/MonsterMusic/releases/tag/0.1.17
