### ISSUE TITLE
app does not start

### ISSUE THREAD

**Issue by gargamel17** [ZTFtrue/MonsterMusic#34]
Hello,
I wanted to try the app, but without success
Phone is poco f1 with los14
App 1.16 from fdroid and 1.17 from github
When app is launched, screen becomes light blue and remains like this until app is killed.
No error message displayed.
Thanks

**Comment by ZTFtrue** [comment]
Hello, are you sure your device system version is los14?  `los14`  is `Android 7.1.x`, and this app never supports `Android 7.1.x` unless you build it by yourself.

Or, isn't los14  lineageos14?

**Comment by gargamel17** [comment]
You are right of course, it is los 21, Android 14 😁
Sorry

Le 1 mai 2024 12:38:57 UTC, ztftrue ***@***.***> a écrit :

**Comment by ZTFtrue** [comment]
Do you have a lot of tracks? Can you tell me how many tracks you have? Are they in a folder? My guess is that scanning for music takes too long.

**Comment by gargamel17** [comment]
Music is stored on se card, there are 20000 files, Size 158 GB.
Storage is ordered by folder :
Artist
-album 1
-album 2
.
.
.

**Comment by ZTFtrue** [comment]
If you have problems, such as tracks not showing up, please let me know
