### ISSUE TITLE
widget

### ISSUE THREAD

**Issue by gargamel17** [ZTFtrue/MonsterMusic#45]
Hello,
Thanks for the latest update.
Do you plan to add a widget ?
Regards

**Comment by ZTFtrue** [comment]
https://github.com/ZTFtrue/MonsterMusic/commit/7f012757ce64c141e46b2bfe544cd7918e8b6626

**Comment by ZTFtrue** [comment]
https://github.com/ZTFtrue/MonsterMusic/releases/tag/0.1.54  Starting from this version, you can set the background of the widget
