### ISSUE TITLE
Sort Songs Numerically

### ISSUE THREAD

**Issue by user44000** [ZTFtrue/MonsterMusic#48]
Could you add an option to sort songs in albums by track number?

**Comment by ZTFtrue** [comment]
There has this feature, name is `Number of songs`

**Comment by user44000** [comment]
I meant sorting songs in an album by the track number of the song. Something like this:
Album Name
Song 1
Song 2
Song 3

**Comment by ZTFtrue** [comment]
OK

**Comment by ZTFtrue** [comment]
added
