### ISSUE TITLE
Show Playlist Duration

### ISSUE THREAD

**Issue by user44000** [ZTFtrue/MonsterMusic#49]
Can you add the duration for albums and the queue?

**Comment by ZTFtrue** [comment]
I don't know where to display the duration on the screen,especially, the queue duration

**Comment by user44000** [comment]
The duration for albums could be displayed in the description of albums under the name and artist. I'm not sure of a good place for the queue duration to be displayed.

**Comment by user44000** [comment]
I'm closing this issue in favor of #80 since there doesn't seem to be a good place to show duration in the queue.
