### ISSUE TITLE
latest version regression

### ISSUE THREAD

**Issue by gargamel17** [ZTFtrue/MonsterMusic#54]
Hello dear, since version 0.1.24 :
- mp3 embedded lyrics are not read anymore
- tracks covers are not displayed anymore in playing screen
Regards

![Screenshot_20240816-085522_MonsterMusic](https://github.com/user-attachments/assets/27120b76-37b3-439d-bcec-27b6c1877b47)
![Screenshot_20240816-085505_MonsterMusic](https://github.com/user-attachments/assets/66550c85-d122-45da-95b3-b52c1591aae5)

**Comment by gargamel17** [comment]
In previous version it was correct

![Screenshot_20240816-085124_MonsterMusic](https://github.com/user-attachments/assets/a9f4574f-2cca-411c-af94-6fb73da74921)
![Screenshot_20240816-085113_MonsterMusic](https://github.com/user-attachments/assets/af957daa-2385-4a85-b8b7-5e02cb43cf67)

**Comment by ZTFtrue** [comment]
Can you send the song file to my email `ztftrue@gmail.com`? Because both this feature is available on my phone.

**Comment by ZTFtrue** [comment]
https://github.com/ZTFtrue/MonsterMusic/releases/tag/0.1.25

**Comment by gargamel17** [comment]
It is now working in 0.1.25, thank you 😀
