### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [ZTFtrue/MonsterMusic#66]
https://github.com/ZTFtrue/MonsterMusic/releases/tag/0.1.30 has no APK

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7832261470#L1056

**Comment by ZTFtrue** [comment]
Thanks. Because 0.1.30 had some bugs, I deleted that version.
Now, I released 0.1.31.

Do I need to re-release 0.1.30?

**Comment by licaon-kter** [comment]
thanks :tada: https://gitlab.com/fdroid/fdroiddata/-/commit/de8a6e29a8bb04a130c42e1b8868c619d2794cc3

**Comment by licaon-kter** [comment]
@ZTFtrue can you rename the tag as per versionName? https://github.com/ZTFtrue/MonsterMusic/blob/0.1.34/app/build.gradle.kts#L26

**Comment by licaon-kter** [comment]
Thanks
